name: Desktop App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Convert line endings to Unix format
        run: dos2unix build.sh

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh
