name: Desktop App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      
      - name: Permissions
        run: sudo chmod +x build.sh

      - name: Run build script
        run: ./build.sh
